const operators = [
{
    id:'43',
    name:'Hotel Ranja',
    about:'Chambre tous comfort et piscine.',
    mail:'ranjahotel@gmail.com',
    phone:'+261 20 75 507 97',
    whatsapp:'+261 20 75 507 97',
    facebook:'Ranja Hotel',
    instat:'ranjahotel',
    web:'www.ranjahotel.mg',
    category:'Hotel',
    categoryIcon:'bed-outline',
    operatorValue:'2',
    language:[],
    profileImage:require('../assets/foretaustrale.jpg'),
    photos:[],
    sites:['Ranomafana'],
    createdAt:''
},
{
    id:'47',
    name:'Mada Tropic',
    about:'Location de voiture',
    mail:'mada@gmail.com',
    phone:'+261 20 75 507 97',
    whatsapp:'+261 20 75 507 97',
    facebook:'Mada Tropic',
    instat:'madatropic',
    web:'www.madatours.com',
    category:'Travel',
    categoryIcon:'earth-outline',
    operatorValue:'2',
    language:[],
    profileImage:require('../assets/madaTropic.png'),
    photos:[],
    sites:['Antananarivo'],
    createdAt:''
},
{
    id:'39',
    name:'Rakotomalala Hery Zo',
    about:'Guide touristique éxperimenté sur le Nord de l\'ile.\r\nLangue:anglais et français',
    mail:'heryzo@gmail.com',
    phone:'+261 20 75 507 97',
    whatsapp:'+261 20 75 507 97',
    facebook:'',
    instat:'',
    web:'',
    category:'Guide',
    categoryIcon:'person-outline',
    operatorValue:'',
    language:['French','English','Espagnol'],
    profileImage:require('../assets/lemurspark.jpg'),
    photos:[],
    sites:['Antananarivo','Andasibe'],
    createdAt:''
},
{
    id:'45',
    name:'Zomatel Fianarantsoa',
    about:'L\'evasion naturel',
    mail:'resa@zomatel.com',
    phone:'+261 20 75 507 97',
    whatsapp:'+261 20 75 507 97',
    facebook:'Zomatel Hôtel - Restaurant',
    instat:'Zomatel Hôtel - Restaurant',
    web:'www.zomatel-fianarantsoa.com',
    category:'Hotel',
    categoryIcon:'home-outline',
    operatorValue:'3',
    language:[],
    profileImage:require('../assets/zoma.jpg'),
    photos:[],
    sites:['Fianarantsoa'],
    createdAt:''
},
{
    id:'77',
    name:'Vannie Hotel',
    about:'Hôtel à Fianarantsoa avec un restaurant et un bar/salon',
    mail:'vanniehotel@gmail.com',
    phone:'+261 20 75 507 97',
    whatsapp:'+261 20 75 507 97',
    facebook:'Vannie Hotel',
    instat:'vanniehotel',
    web:'www.vanniehotel.com',
    category:'Hotel',
    categoryIcon:'home-outline',
    operatorValue:'2',
    language:[],
    profileImage:require('../assets/vannie.jpg'),
    photos:[],
    sites:['Fianarantsoa'],
    createdAt:''
}
    ]


export default operators;